Add placeholder security and privacy considerations section
WICG/digital-credentials pull request #148
Opened 2024-07-24 17:34 UTC by timcappalli

Resolves #137 

The following tasks have been completed:

- [ ] Modified Web platform tests (link)

Implementation commitment:

- [ ] WebKit (link to issue)
- [ ] Chromium (link to issue)
- [ ] Gecko (link to issue)

Documentation and checks

- [ ] Affects privacy
- [ ] Affects security
- [ ] Pinged MDN
- [ ] Updated Explainer

2024-07-24 17:46 UTC, TallTed requested changes

2024-07-24 17:46 UTC, TallTed commented on index.html
> +        The documents listed below outline various privacy and security considerations for Digital Credentials, both broadly and for presentation on the web. Their contents will be integrated into th
```suggestion
        The documents listed below outline various privacy and security considerations for Digital Credentials, both broadly and for presentation on the web. Their contents will be integrated into this document gradually.
```

2024-07-24 17:46 UTC, TallTed commented on index.html
> +        <li><a href="https://github.com/w3cping/credential-considerations">W3C Privacy Interest Group (PING) Credentials Considerations repository</a> which contains in-progress list of concerns and
```suggestion
        <li><a href="https://github.com/WICG/digital-credentials/blob/main/horizontal-reviews/security-privacy.md">TAG Security and Privacy Considerations Questionnaire (WIP)</a></li>
        <li><a href="https://github.com/w3cping/credential-considerations">W3C Privacy Interest Group (PING) Credentials Considerations repository</a> which contains in-progress list of concerns and implications of identity-verification and credential presentation, for consideration in Internet and Web standardization</li>
```

2024-07-24 22:15 UTC, marcoscaceres commented on index.html
> +    </section>
As much as I like the explainer, I'm not sure it's worth listing it tbh. It's also good to include the accessibility considerations while we are here. 

```suggestion
    <section class="informative">
      <h2>
        Security Considerations
      </h2>
      <p class="issue" title="Work in Progress">
        This section is a work in progress as this document evolves.
      </p>
      <p>
        The documents listed below outline initial security considerations for Digital Credentials, both broadly and for presentation on the web. Their contents will be integrated into this document gradually.
      </p>
      <ul>
        <li><a href="https://github.com/WICG/digital-credentials/blob/main/horizontal-reviews/security-privacy.md">TAG Security and Privacy Considerations Questionnaire (WIP)</a></li>
      </ul>
    </section>
    <section class="informative">
      <h2>
        Privacy Considerations
      </h2>
      <p class="issue" title="Work in Progress">
        This section is a work in progress as this document evolves.
      </p>
      <p>
        The documents listed below outline various privacy considerations for Digital Credentials, both broadly and for presentation on the web. Their contents will be integrated into this document gradually.
      </p>
      <ul>
        <li><a href="https://github.com/WICG/digital-credentials/blob/main/horizontal-reviews/security-privacy.md">TAG Security and Privacy Considerations Questionnaire (WIP)</a></li>
        <li><a href="https://github.com/w3cping/credential-considerations">W3C Privacy Interest Group (PING) Credentials Considerations repository</a> which contains in-progress list of concerns and implications of identity-verification and credential presentation, for consideration in Internet and Web standardization</li>
      </ul>
    </section>
    <section class="informative">
      <h2>
        Accessibility Considerations
      </h2>
      <p class="issue" title="Work in Progress">
        This section is a work in progress as this document evolves.
      </p>
    </section>
```

2024-07-26 09:14 UTC, marcoscaceres approved these changes

2024-07-26 10:52 UTC, vinniespina approved these changes

2024-07-26 10:52 UTC, vinniespina approved these changes

2024-07-26 10:53 UTC, vinniespina approved these changes

2024-07-26 10:53 UTC, vinniespina approved these changes

2024-07-26 10:54 UTC, vinniespina approved these changes

2024-07-26 10:55 UTC, vinniespina approved these changes

2024-07-26 10:55 UTC, vinniespina approved these changes

2024-07-26 10:55 UTC, vinniespina approved these changes

2024-07-26 10:55 UTC, vinniespina approved these changes

2024-07-26 10:55 UTC, vinniespina approved these changes

2024-07-26 10:56 UTC, vinniespina approved these changes

2024-07-26 10:56 UTC, vinniespina approved these changes

2024-07-26 10:56 UTC, vinniespina approved these changes

2024-07-26 10:56 UTC, vinniespina approved these changes

2024-07-26 10:56 UTC, vinniespina approved these changes

2024-07-26 10:56 UTC, vinniespina approved these changes

2024-07-26 10:57 UTC, vinniespina approved these changes

2024-07-26 10:57 UTC, vinniespina approved these changes

2024-07-26 10:57 UTC, vinniespina approved these changes

2024-07-26 10:57 UTC, vinniespina approved these changes

2024-07-26 10:57 UTC, vinniespina approved these changes

2024-07-26 10:57 UTC, vinniespina approved these changes

2024-07-26 10:58 UTC, vinniespina approved these changes

2024-07-26 10:58 UTC, vinniespina approved these changes

2024-07-26 10:58 UTC, vinniespina approved these changes

2024-07-26 10:58 UTC, vinniespina approved these changes

2024-07-26 10:58 UTC, vinniespina approved these changes

2024-07-26 10:59 UTC, vinniespina approved these changes

2024-07-26 10:59 UTC, vinniespina approved these changes

2024-07-26 10:59 UTC, vinniespina approved these changes

2024-07-26 10:59 UTC, vinniespina approved these changes

2024-07-26 10:59 UTC, vinniespina approved these changes

2024-07-26 10:59 UTC, vinniespina approved these changes

2024-07-26 11:00 UTC, vinniespina approved these changes

2024-07-26 11:00 UTC, vinniespina approved these changes

2024-07-26 11:00 UTC, vinniespina approved these changes

2024-07-26 11:00 UTC, vinniespina approved these changes

2024-07-26 11:00 UTC, vinniespina approved these changes

2024-07-26 11:01 UTC, vinniespina approved these changes

2024-07-26 11:01 UTC, vinniespina approved these changes

2024-07-26 11:01 UTC, vinniespina approved these changes

2024-07-26 11:02 UTC, vinniespina approved these changes

2024-07-26 11:02 UTC, vinniespina approved these changes

2024-07-26 11:02 UTC, vinniespina approved these changes

2024-07-26 11:02 UTC, vinniespina approved these changes

2024-07-26 11:02 UTC, vinniespina approved these changes

2024-07-26 11:36 UTC, vinniespina approved these changes

2024-07-26 11:36 UTC, vinniespina approved these changes

2024-07-26 11:36 UTC, vinniespina approved these changes

2024-07-26 11:36 UTC, vinniespina approved these changes

2024-07-26 11:36 UTC, vinniespina approved these changes

2024-07-26 11:37 UTC, vinniespina approved these changes

2024-07-26 11:37 UTC, vinniespina approved these changes

2024-07-26 11:45 UTC, vinniespina approved these changes

2024-07-26 11:46 UTC, vinniespina approved these changes

2024-07-26 11:46 UTC, vinniespina approved these changes

2024-07-26 11:46 UTC, vinniespina approved these changes

2024-07-26 11:47 UTC, vinniespina approved these changes

2024-07-26 11:47 UTC, vinniespina approved these changes

2024-07-26 11:47 UTC, vinniespina approved these changes

2024-07-26 11:47 UTC, vinniespina approved these changes

2024-07-26 11:47 UTC, vinniespina approved these changes

2024-07-26 11:47 UTC, vinniespina approved these changes

2024-07-26 11:48 UTC, vinniespina approved these changes

2024-07-30 04:30 UTC, merged