Add required mediation
WICG/digital-credentials pull request #149
Opened 2024-07-30 03:41 UTC by marcoscaceres

Closes #147 

The following tasks have been completed:

- [ ] Modified Web platform tests (link)

Implementation commitment:

- [ ] WebKit (link to issue)
- [ ] Chromium (link to issue)
- [ ] Gecko (link to issue)

Documentation and checks

- [ ] Affects privacy
- [ ] Affects security
- [ ] Pinged MDN
- [ ] Updated Explainer

2024-08-01 20:06 UTC, timcappalli approved these changes

2024-08-01 21:54 UTC, OR13 approved these changes

2024-08-02 18:30 UTC, bvandersloot-mozilla reviewed
I think that `"optional"` would also be acceptable here. That would be the page telling the browser that it may show UI, which is all that is being validated, correct?

2024-08-05 02:30 UTC, marcoscaceres commented
@bvandersloot-mozilla, right. I guess it depends on how you read the definition of "optional" from Cred Man: 

> **optional**: If credentials can be handed over for a given operation without user mediation, they will be. If [user mediation is required](https://w3c.github.io/webappsec-credential-management/#origin-requires-user-mediation), then the user agent will involve the user in the decision.

My reading from the above, and what I'm worried about, is that leaving it as "optional" invites optionality in presenting UI (which presuppose is always "required"). 

For completeness, here is how required is defined:

> **required**: The user agent will not hand over credentials without [user mediation](https://w3c.github.io/webappsec-credential-management/#user-mediated), even if the [prevent silent access flag](https://w3c.github.io/webappsec-credential-management/#origin-prevent-silent-access-flag) is unset for an origin.

2024-08-05 02:34 UTC, marcoscaceres commented
So, I guess we could do things differently... we could state in the spec that "mediation is always required" for this kind of credential, but we need to fix https://github.com/w3c/webappsec-credential-management/issues/248 ... that could allow "optional", but enforce showing UI in prose and in Cred Man.

2024-08-13 07:19 UTC, marcoscaceres commented
@samuelgoto, wouldn't mind your thoughts on this.

2024-08-21 06:14 UTC, marcoscaceres commented
Ok, so, yeah... per step 8.1 of of Cred Man:

> If options.[mediation](https://w3c.github.io/webappsec-credential-management/#dom-credentialrequestoptions-mediation) is [conditional](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional) and interface does not support [conditional](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional) [user mediation](https://w3c.github.io/webappsec-credential-management/#user-mediated), return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) a "[TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).

So, we actually just need to state that mediation is required but not as part of the algorithm... will fix.

2024-08-21 06:48 UTC, marcoscaceres commented
@TallTed 🦅 👀 🙏? ... 😊

2024-08-22 17:59 UTC, TallTed requested changes
Small, human-facing.

2024-08-22 17:59 UTC, TallTed commented on index.html
> +      {{TypeError}} when {{CredentialsContainer/get()}} is called.
```suggestion
      {{CredentialMediationRequirement/"required"}}. The only supported
      {{CredentialMediationRequirement}} enum value is
      {{CredentialMediationRequirement/"required"}}, which results in a
      {{TypeError}} when {{CredentialsContainer/get()}} is called.
```

2024-08-22 19:32 UTC, samuelgoto approved these changes
LGTM++

> I think that "optional" would also be acceptable here. That would be the page telling the browser that it may show UI, which is all that is being validated, correct?

I share the intuition that we may want to support `optional` too at some point, but I think we can cross the bridge of `optional` when we get there without cornering ourselves.

2024-08-23 00:42 UTC, marcoscaceres commented
For "required" and "optional"... I think I have a better solution for all this:
https://github.com/w3c/webappsec-credential-management/issues/256

We need fix the Cred Man API to allow us to set our own default.

2024-08-23 02:31 UTC, marcoscaceres commented
@samuelgoto, @bvandersloot-mozilla, here's a first stab at fixing this in Cred Man:
https://github.com/w3c/webappsec-credential-management/pull/258

2024-08-23 02:38 UTC, marcoscaceres commented
For those watching at home, this would mean that the following would not throw:

```JS
navigator.identity.get({digital: ...}); // this throws today, which is annoying. 
navigator.identity.get({digital: ..., mediation: "required"});
```

2024-08-23 02:42 UTC, marcoscaceres commented
(also, `"optional"` mentioned by a few folks above is meant to be `"conditional"`... yay, naming things if fun 😜)

2024-08-23 16:55 UTC, samuelgoto commented
> (also, "optional" mentioned by a few folks above is meant to be "conditional"... yay, naming things if fun 😜)

I'm not sure I follow this reference, but I was actually discussion `optional` rather than `conditional` as:

https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-optional

2024-08-24 03:05 UTC, marcoscaceres commented
Sorry @samuelgoto, I might have confused myself 🙈

2024-08-26 22:34 UTC, samuelgoto approved these changes
LGTM++

Just a few minor clarifications.

2024-08-26 22:34 UTC, samuelgoto commented on index.html
> +      not support {{CredentialMediationRequirement/"conditional"}} [=user
```suggestion
      not support {{CredentialMediationRequirement/"conditional"}} and {{CredentialMediationRequirement/"optional"}} and {{CredentialMediationRequirement/"silent"}} [=user
```

2024-08-26 22:34 UTC, samuelgoto commented on index.html
> +      {{TypeError}} when {{CredentialsContainer/get()}} is called.
```suggestion
      {{TypeError}} when {{CredentialsContainer/get()}} is called with anything but {{CredentialMediationRequirement/"required"}}.
```

2024-08-26 22:37 UTC, samuelgoto commented
(added chromium bug for implementation)

2024-08-27 01:31 UTC, marcoscaceres commented on index.html
> +    </p>
```suggestion
    [=User mediation=] is always {{CredentialMediationRequirement/"required"}}.
    [=Request a credential|Requesting a DigitalCredential credential=] does not support {{CredentialMediationRequirement/"conditional"}}, {{CredentialMediationRequirement/"optional"}}, or {{CredentialMediationRequirement/"silent"}} [=user mediation=]. If {{CredentialsContainer/get()}} is called with anything other than {{CredentialMediationRequirement/"required"}}, a {{TypeError}} will be thrown.
    </p>
```

2024-08-27 01:31 UTC, merged

2024-09-19 20:24 UTC, samuelgoto commented
As we were implementing this PR, something occurred to us:

(a) first, this is a backwards incompatible change for us: `mediation` is an optional field and it defaults to `optional`, so some developers have been using the default value.
(b) second, is excluding `optional` really required? meaning, isn't the website leaving the choice to the user agent when they choose `optional`? meaning, wouldn't a valid implementation of `optional` be to threat it as `required`?

If this is correct, then can we make this more flexible and also allow the default value to be used, `optional` (and allow each implementation to implement it in whichever way it see fit)?

2024-10-07 21:24 UTC, samuelgoto commented
> As we were implementing this PR here, something occurred to me while reviewing it:

FWIW, we found a resolution to this here:

https://github.com/WICG/digital-credentials/issues/175#issuecomment-2397438963